/**
 * createTestStore — typed configureStore factory for unit tests.
 *
 * Generated by /devkit:cover --setup. Lives in src/__tests__/utils/.
 *
 * For thunk tests, prefer the inline stub-reducer pattern instead:
 *   const makeStore = () => configureStore({ reducer: () => ({}) });
 *
 * Use createTestStore when you need a real store with combined slice
 * reducers and a focused preloadedState — typically for Redux-aware hook
 * tests and container tests.
 */
import { configureStore, type Reducer } from '@reduxjs/toolkit';

interface CreateTestStoreOpts<TState> {
  reducer: Reducer<TState>;
  preloadedState?: Partial<TState>;
}

export const createTestStore = <TState>(
  opts: CreateTestStoreOpts<TState>,
) =>
  configureStore({
    reducer: opts.reducer,
    preloadedState: opts.preloadedState as TState,
    middleware: gDM => gDM({ serializableCheck: false, immutableCheck: false }),
  });
