/**
 * navigationMock — spy factory for React Navigation prop mocks.
 *
 * Generated by /devkit:cover --setup. Lives in src/__tests__/utils/.
 *
 * Pass into containers/components that take a `navigation` prop directly:
 *   const nav = makeNavigation();
 *   render(<MyScreen navigation={nav} />);
 *   fireEvent.press(getByText('Next'));
 *   expect(nav.navigate).toHaveBeenCalledWith('OtherScreen');
 */
export const makeNavigation = () => ({
  navigate: jest.fn(),
  goBack: jest.fn(),
  replace: jest.fn(),
  push: jest.fn(),
  pop: jest.fn(),
  reset: jest.fn(),
  setParams: jest.fn(),
  setOptions: jest.fn(),
  addListener: jest.fn(() => () => {}),
  isFocused: jest.fn(() => true),
  canGoBack: jest.fn(() => true),
});
