/**
 * renderWithProviders — wraps a component under all providers a real screen
 * would have. Used by container tests.
 *
 * Generated by /devkit:cover --setup. Lives in src/__tests__/utils/.
 *
 * The wrapped tree mounts:
 *   - Redux Provider (using createTestStore — focused store, not the real one)
 *   - SafeAreaProvider (with zero insets — see __mocks__/react-native-safe-area-context)
 *   - NavigationContainer (for hooks that read navigation context)
 *
 * Placeholders the command resolves:
 *   {{ rootReducerImport }} — typically: from '@store/rootReducer'
 *   {{ rootStateImport }}   — typically: from '@store/index'
 */
import React, { ReactElement } from 'react';
import { render, RenderOptions } from '@testing-library/react-native';
import { Provider } from 'react-redux';
import { NavigationContainer } from '@react-navigation/native';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import { createTestStore } from './createTestStore';
{{ rootReducerImport }}
{{ rootStateImport }}

interface Options extends Omit<RenderOptions, 'wrapper'> {
  preloadedState?: Partial<RootState>;
  store?: ReturnType<typeof createTestStore<RootState>>;
}

export const renderWithProviders = (
  ui: ReactElement,
  { preloadedState, store = createTestStore({ reducer: rootReducer, preloadedState }), ...rest }: Options = {},
) => {
  const Wrapper: React.FC<{ children: React.ReactNode }> = ({ children }) => (
    <Provider store={store}>
      <SafeAreaProvider>
        <NavigationContainer>{children}</NavigationContainer>
      </SafeAreaProvider>
    </Provider>
  );
  return { store, ...render(ui, { wrapper: Wrapper, ...rest }) };
};
