/**
 * Global Jest setup — generated by /devkit:cover --setup.
 *
 * Loaded via `setupFiles` in jest.config.js. Runs once per test file, BEFORE
 * the test framework is set up and before any test imports run.
 *
 * Conventions:
 *  - Module-level `jest.mock(...)` for app-wide concerns lives here.
 *  - Per-package native module shims live in `<package>/__mocks__/` (Jest
 *    auto-discovers via the `__mocks__/` convention).
 *  - Test-file-specific mocks (e.g. per-test apiClient returns) stay inline
 *    at the top of the individual test file.
 *
 * Placeholders the command resolves:
 *   {{ apiFetchAlias }}      — typically '@api/fetch'
 *   {{ storeIndexAlias }}    — typically '@store/index'
 *   {{ providerUtilsAlias }} — typically '@provider-utils/ErrorUtil'
 *   {{ nativeNavigatorName }}— typically 'RNNativeNavigator'
 */

// ─── Break circular import chain through @api/fetch ──────────────────────────
//
// API base-URL helpers often eagerly require the store at module load time.
// When a test enters through a service or thunk file, that chain circles back
// and crashes mid-init (the slice tries to use a still-undefined thunk export
// inside its extraReducers). Mocking the URL helpers short-circuits the cycle
// without affecting production code.
jest.mock('{{ apiFetchAlias }}', () => ({
  __esModule: true,
  getUrl: jest.fn((type: string) => `https://test.example.com/${type}`),
  getCurrentDomain: jest.fn(() => 'https://test.example.com/'),
  getBaseUrls: jest.fn(() => ({
    BASE_URL: 'https://test.example.com/api',
    MASTER_BASE_URL: 'https://test.example.com/api',
    SIGNED_URL: 'https://test.example.com/api',
  })),
  getDomainFromStagingName: jest.fn(() => 'https://test.example.com/'),
}));

// ─── Store singleton stub ────────────────────────────────────────────────────
//
// apiClient often imports the real store at module load time. Loading the
// real store triggers the listener middleware chain, which references thunk
// action creators by name during registration. When a test enters through a
// service or slice file, those thunk modules are still mid-load → references
// are `undefined` → crashes like "Cannot read properties of undefined
// (reading 'fulfilled')".
//
// Tests never need the production singleton — they build a focused store
// with configureStore + preloadedState. So we stub the singleton here.
jest.mock('{{ storeIndexAlias }}', () => ({
  __esModule: true,
  store: {
    dispatch: jest.fn(),
    getState: jest.fn(() => ({})),
    subscribe: jest.fn(),
    replaceReducer: jest.fn(),
  },
}));

// ─── Native bridge stub ──────────────────────────────────────────────────────
//
// {{ nativeNavigatorName }} is the bridge the package's RN code calls to
// navigate back to native screens. Stubbed as jest.fn so tests can assert
// calls without crashing.
jest.mock('react-native', () => {
  const RN = jest.requireActual('react-native');
  RN.NativeModules.{{ nativeNavigatorName }} = {
    navigateToProfileHome: jest.fn(),
    navigateToOnboardingWithRoute: jest.fn(),
    navigateToOnboardingWithRouteAndClearStack: jest.fn(),
    navigateToEstSearchAndAdd: jest.fn(),
  };
  return RN;
});

// ─── Silence production-code dev loggers in tests ───────────────────────────
//
// log / logError / logWarning in {{ providerUtilsAlias }} are guarded by
// __DEV__ and emit to console.* in dev. In tests, __DEV__ is truthy, so every
// error-path test (where we intentionally trigger a rejection to verify it
// propagates) ends up printing the production logError output.
jest.mock('{{ providerUtilsAlias }}', () => ({
  __esModule: true,
  log: jest.fn(),
  logError: jest.fn(),
  logWarning: jest.fn(),
}));
