/**
 * Mongoose test helpers. Generated by /devkit:cover --setup.
 *
 * Factories for the Mongoose objects that managers/repositories touch most:
 * ClientSession (transactions) and lightweight query builders. Extend as the
 * suite grows — keep factories small and override-friendly.
 */

/**
 * A mock Mongoose ClientSession with every lifecycle method the transaction
 * code calls. `inTransaction` defaults to true so the error path attempts an
 * abort — override per test where needed: `makeSession({ inTransaction: () => false })`.
 */
export const makeSession = (overrides: Partial<Record<string, unknown>> = {}) => ({
  startTransaction: jest.fn().mockResolvedValue(undefined),
  commitTransaction: jest.fn().mockResolvedValue(undefined),
  abortTransaction: jest.fn().mockResolvedValue(undefined),
  endSession: jest.fn().mockResolvedValue(undefined),
  inTransaction: jest.fn().mockReturnValue(true),
  ...overrides,
});

/**
 * A chainable mock Mongoose Query (`.populate().lean().session().exec()` etc.)
 * that finally resolves to `result`. Add chain methods your model code uses.
 */
export const makeQuery = (result: unknown) => {
  const query: Record<string, jest.Mock> = {};
  ['populate', 'lean', 'session', 'sort', 'select', 'limit', 'skip'].forEach((m) => {
    query[m] = jest.fn(() => query);
  });
  query.exec = jest.fn().mockResolvedValue(result);
  // Allow `await query` directly (thenable).
  (query as unknown as { then: unknown }).then = (resolve: (v: unknown) => void) =>
    resolve(result);
  return query;
};
