/**
 * Global Jest setup for the Node.js / TypeScript service.
 * Loaded via jest.config.js `setupFiles`. Runs once before the test files.
 *
 * Generated by /devkit:cover --setup.
 */

// TypeDI / class decorators require reflect-metadata to be imported exactly once,
// before any decorated class is loaded. Keep this as the FIRST import.
import 'reflect-metadata';

// Make the environment deterministic for tests.
process.env.NODE_ENV = process.env.NODE_ENV || 'test';

// Silence noisy structured loggers during tests. Replace these module paths
// with the project's real logger entrypoints (graylog / opentelemetry / pino).
//
// jest.mock('{{ loggerModule }}', () => ({
//   logger: { info: jest.fn(), warn: jest.fn(), error: jest.fn(), debug: jest.fn() },
// }));
