/**
 * TypeDI test helper. Generated by /devkit:cover --setup.
 *
 * Resets the global TypeDI container between tests so registered singletons,
 * overridden services, and injected mocks from one test never bleed into the
 * next. Call resetContainer() in both beforeEach and afterEach.
 */
import { Container } from 'typedi';

/** Clears all registered services/values from the global TypeDI container. */
export const resetContainer = (): void => {
  Container.reset();
};
